"""Theme presets for Pedal Architect."""

THEME_PRESET_SPECS = [
    ("dark", "Dark"),
    ("light", "Light"),
    ("sunset", "Sunset"),
    ("ocean", "Ocean"),
    ("prism", "Prism (Floyd)"),
    ("brown_sound", "Brown Sound (VH)"),
    ("paisley", "Paisley Prairie"),
]

THEMES = {
    "dark": {
        "bg": "#11161a",
        "text": "#e9efe4",
        "frame": "#3a464e",
        "panel": "#161f25",
        "tab": "#1d252b",
        "tab_selected_bg": "#d6fd73",
        "tab_selected_fg": "#1a230f",
        "group_title": "#d6e2cb",
        "canvas_bg": "#0f1418",
        "canvas_grid": "#202b33",
        "canvas_edge": "#86c7ff",
        "canvas_edge_preview": "#86c7ff",
        "amp_bg": "#232f38",
        "amp_fg": "#f3f8f0",
        "positive": "#66d17a",
    },
    "light": {
        "bg": "#f5f6f8",
        "text": "#21252b",
        "frame": "#c0c7d1",
        "panel": "#ffffff",
        "tab": "#e7ebf0",
        "tab_selected_bg": "#2f6feb",
        "tab_selected_fg": "#ffffff",
        "group_title": "#253347",
        "canvas_bg": "#edf1f6",
        "canvas_grid": "#d0d8e4",
        "canvas_edge": "#1f6feb",
        "canvas_edge_preview": "#1f6feb",
        "amp_bg": "#d7e1ec",
        "amp_fg": "#1f2f42",
        "positive": "#1f8a3d",
    },
    "sunset": {
        "bg": "#2a1d22",
        "text": "#f7e8da",
        "frame": "#7f4a53",
        "panel": "#3a262d",
        "tab": "#4a3038",
        "tab_selected_bg": "#ffb347",
        "tab_selected_fg": "#3a2523",
        "group_title": "#ffcf97",
        "canvas_bg": "#2e1d24",
        "canvas_grid": "#5d3943",
        "canvas_edge": "#ffd166",
        "canvas_edge_preview": "#ffd166",
        "amp_bg": "#5a3031",
        "amp_fg": "#ffe9c4",
        "positive": "#9ce26a",
    },
    "ocean": {
        "bg": "#0f2430",
        "text": "#def1f6",
        "frame": "#2f6172",
        "panel": "#123544",
        "tab": "#164454",
        "tab_selected_bg": "#2ad4c5",
        "tab_selected_fg": "#0f2831",
        "group_title": "#a5e8df",
        "canvas_bg": "#0d2a36",
        "canvas_grid": "#235062",
        "canvas_edge": "#6ee7ff",
        "canvas_edge_preview": "#6ee7ff",
        "amp_bg": "#1c4a5a",
        "amp_fg": "#ddfbff",
        "positive": "#58d39e",
    },
    "prism": {
        "bg": "#11101b",
        "text": "#f5f4ff",
        "frame": "#544f73",
        "panel": "#1a1830",
        "tab": "#242147",
        "tab_selected_bg": "#74efff",
        "tab_selected_fg": "#111327",
        "group_title": "#f6d7ff",
        "canvas_bg": "#120f22",
        "canvas_grid": "#2f2a56",
        "canvas_edge": "#ffd268",
        "canvas_edge_preview": "#ffd268",
        "amp_bg": "#2d2541",
        "amp_fg": "#fff3de",
        "positive": "#8cffaa",
    },
    "brown_sound": {
        "bg": "#1a1110",
        "text": "#ffe7d2",
        "frame": "#6f3f37",
        "panel": "#291716",
        "tab": "#3a1e1b",
        "tab_selected_bg": "#e03e31",
        "tab_selected_fg": "#fff6ec",
        "group_title": "#ffb184",
        "canvas_bg": "#1f1211",
        "canvas_grid": "#4a2a26",
        "canvas_edge": "#ff8a3b",
        "canvas_edge_preview": "#ff8a3b",
        "amp_bg": "#41231e",
        "amp_fg": "#ffe9d1",
        "positive": "#ffd166",
    },
    "paisley": {
        "bg": "#f4efe3",
        "text": "#243033",
        "frame": "#9fb4a9",
        "panel": "#fffdf7",
        "tab": "#e3efe8",
        "tab_selected_bg": "#3e8f68",
        "tab_selected_fg": "#effff4",
        "group_title": "#3f5d55",
        "canvas_bg": "#ecf4ef",
        "canvas_grid": "#c5dbd1",
        "canvas_edge": "#2f6a90",
        "canvas_edge_preview": "#2f6a90",
        "amp_bg": "#d4e6dc",
        "amp_fg": "#1f3f37",
        "positive": "#2c9d68",
    },
}
