"""Theme presets for Pedal Architect."""

THEME_PRESET_SPECS = [
    ("dark", "Dark"),
    ("light", "Light"),
    ("sunset", "Sunset"),
    ("ocean", "Ocean"),
    ("prism", "Prism (Floyd)"),
    ("brown_sound", "Brown Sound (VH)"),
    ("paisley", "Paisley Prairie"),
    ("monokai_npp", "Notepad++ Monokai"),
    ("obsidian_npp", "Notepad++ Obsidian"),
    ("twilight_npp", "Notepad++ Twilight"),
    ("deep_black_npp", "Notepad++ Deep Black"),
    ("zenburn_npp", "Notepad++ Zenburn"),
]

THEMES = {
    "dark": {
        "bg": "#11161a",
        "text": "#e9efe4",
        "frame": "#3a464e",
        "panel": "#161f25",
        "tab": "#1d252b",
        "tab_selected_bg": "#d6fd73",
        "tab_selected_fg": "#1a230f",
        "group_title": "#d6e2cb",
        "canvas_bg": "#0f1418",
        "canvas_grid": "#202b33",
        "canvas_edge": "#86c7ff",
        "canvas_edge_preview": "#86c7ff",
        "amp_bg": "#232f38",
        "amp_fg": "#f3f8f0",
        "positive": "#66d17a",
        "root_note": "#ff5c63",
        "scale_note": "#66d17a",
    },
    "light": {
        "bg": "#f5f6f8",
        "text": "#21252b",
        "frame": "#c0c7d1",
        "panel": "#ffffff",
        "tab": "#e7ebf0",
        "tab_selected_bg": "#2f6feb",
        "tab_selected_fg": "#ffffff",
        "group_title": "#253347",
        "canvas_bg": "#edf1f6",
        "canvas_grid": "#d0d8e4",
        "canvas_edge": "#1f6feb",
        "canvas_edge_preview": "#1f6feb",
        "amp_bg": "#d7e1ec",
        "amp_fg": "#1f2f42",
        "positive": "#1f8a3d",
        "root_note": "#d61f35",
        "scale_note": "#1f8a3d",
    },
    "sunset": {
        "bg": "#2a1d22",
        "text": "#f7e8da",
        "frame": "#7f4a53",
        "panel": "#3a262d",
        "tab": "#4a3038",
        "tab_selected_bg": "#ffb347",
        "tab_selected_fg": "#3a2523",
        "group_title": "#ffcf97",
        "canvas_bg": "#2e1d24",
        "canvas_grid": "#5d3943",
        "canvas_edge": "#ffd166",
        "canvas_edge_preview": "#ffd166",
        "amp_bg": "#5a3031",
        "amp_fg": "#ffe9c4",
        "positive": "#9ce26a",
        "root_note": "#ff5c66",
        "scale_note": "#9ce26a",
    },
    "ocean": {
        "bg": "#0f2430",
        "text": "#def1f6",
        "frame": "#2f6172",
        "panel": "#123544",
        "tab": "#164454",
        "tab_selected_bg": "#2ad4c5",
        "tab_selected_fg": "#0f2831",
        "group_title": "#a5e8df",
        "canvas_bg": "#0d2a36",
        "canvas_grid": "#235062",
        "canvas_edge": "#6ee7ff",
        "canvas_edge_preview": "#6ee7ff",
        "amp_bg": "#1c4a5a",
        "amp_fg": "#ddfbff",
        "positive": "#58d39e",
        "root_note": "#ff6a73",
        "scale_note": "#58d39e",
    },
    "prism": {
        "bg": "#11101b",
        "text": "#f5f4ff",
        "frame": "#544f73",
        "panel": "#1a1830",
        "tab": "#242147",
        "tab_selected_bg": "#74efff",
        "tab_selected_fg": "#111327",
        "group_title": "#f6d7ff",
        "canvas_bg": "#120f22",
        "canvas_grid": "#2f2a56",
        "canvas_edge": "#ffd268",
        "canvas_edge_preview": "#ffd268",
        "amp_bg": "#2d2541",
        "amp_fg": "#fff3de",
        "positive": "#8cffaa",
        "root_note": "#ff7f4f",
        "scale_note": "#8cffaa",
    },
    "brown_sound": {
        "bg": "#1a1110",
        "text": "#ffe7d2",
        "frame": "#6f3f37",
        "panel": "#291716",
        "tab": "#3a1e1b",
        "tab_selected_bg": "#e03e31",
        "tab_selected_fg": "#fff6ec",
        "group_title": "#ffb184",
        "canvas_bg": "#1f1211",
        "canvas_grid": "#4a2a26",
        "canvas_edge": "#ff8a3b",
        "canvas_edge_preview": "#ff8a3b",
        "amp_bg": "#41231e",
        "amp_fg": "#ffe9d1",
        "positive": "#ffd166",
        "root_note": "#ff5148",
        "scale_note": "#ffd166",
    },
    "paisley": {
        "bg": "#f4efe3",
        "text": "#243033",
        "frame": "#9fb4a9",
        "panel": "#fffdf7",
        "tab": "#e3efe8",
        "tab_selected_bg": "#3e8f68",
        "tab_selected_fg": "#effff4",
        "group_title": "#3f5d55",
        "canvas_bg": "#ecf4ef",
        "canvas_grid": "#c5dbd1",
        "canvas_edge": "#2f6a90",
        "canvas_edge_preview": "#2f6a90",
        "amp_bg": "#d4e6dc",
        "amp_fg": "#1f3f37",
        "positive": "#2c9d68",
        "root_note": "#d63d5a",
        "scale_note": "#2c9d68",
    },
    "monokai_npp": {
        "bg": "#272822",
        "text": "#f8f8f2",
        "frame": "#555747",
        "panel": "#2e2f28",
        "tab": "#35362f",
        "tab_selected_bg": "#a6e22e",
        "tab_selected_fg": "#1f2513",
        "group_title": "#f0ffb8",
        "canvas_bg": "#23241f",
        "canvas_grid": "#3a3c33",
        "canvas_edge": "#66d9ef",
        "canvas_edge_preview": "#66d9ef",
        "amp_bg": "#3a3c33",
        "amp_fg": "#f8f8f2",
        "positive": "#66d9ef",
        "root_note": "#fd5e7f",
        "scale_note": "#66d9ef",
    },
    "obsidian_npp": {
        "bg": "#293134",
        "text": "#e0e2e4",
        "frame": "#465056",
        "panel": "#313b3f",
        "tab": "#364146",
        "tab_selected_bg": "#ffd479",
        "tab_selected_fg": "#2a2f31",
        "group_title": "#f6e3bd",
        "canvas_bg": "#242c2f",
        "canvas_grid": "#3a454a",
        "canvas_edge": "#8ec5ff",
        "canvas_edge_preview": "#8ec5ff",
        "amp_bg": "#3a454a",
        "amp_fg": "#f2f5f7",
        "positive": "#7bc79e",
        "root_note": "#ff6c6c",
        "scale_note": "#7bc79e",
    },
    "twilight_npp": {
        "bg": "#141414",
        "text": "#f7f7f7",
        "frame": "#545454",
        "panel": "#1f1f1f",
        "tab": "#2a2a2a",
        "tab_selected_bg": "#ffcc66",
        "tab_selected_fg": "#201b12",
        "group_title": "#ffdba0",
        "canvas_bg": "#111111",
        "canvas_grid": "#2c2c2c",
        "canvas_edge": "#82aaff",
        "canvas_edge_preview": "#82aaff",
        "amp_bg": "#2a2a2a",
        "amp_fg": "#f6f6f6",
        "positive": "#99d090",
        "root_note": "#ff5e73",
        "scale_note": "#99d090",
    },
    "deep_black_npp": {
        "bg": "#050505",
        "text": "#f2f2f2",
        "frame": "#323232",
        "panel": "#0f0f0f",
        "tab": "#1a1a1a",
        "tab_selected_bg": "#ffae42",
        "tab_selected_fg": "#1d1508",
        "group_title": "#ffd594",
        "canvas_bg": "#050505",
        "canvas_grid": "#1c1c1c",
        "canvas_edge": "#58b7ff",
        "canvas_edge_preview": "#58b7ff",
        "amp_bg": "#1a1a1a",
        "amp_fg": "#f2f2f2",
        "positive": "#7cd992",
        "root_note": "#ff5a66",
        "scale_note": "#7cd992",
    },
    "zenburn_npp": {
        "bg": "#3f3f3f",
        "text": "#dcdccc",
        "frame": "#6a7169",
        "panel": "#4a4a4a",
        "tab": "#545b54",
        "tab_selected_bg": "#8faf9f",
        "tab_selected_fg": "#1f2621",
        "group_title": "#d7d7af",
        "canvas_bg": "#383838",
        "canvas_grid": "#525252",
        "canvas_edge": "#93e0e3",
        "canvas_edge_preview": "#93e0e3",
        "amp_bg": "#545b54",
        "amp_fg": "#ececd0",
        "positive": "#9fc59f",
        "root_note": "#df6f7a",
        "scale_note": "#9fc59f",
    },
}
